# Generated by Django 4.0.4 on 2022-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allergy',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
