# Generated by Django 4.0.4 on 2022-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_robot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
