# Generated by Django 4.0.4 on 2022-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simptom',
            name='pills',
            field=models.ManyToManyField(related_name='simptoms', through='pill.SimptomPill', to='pill.pill'),
        ),
    ]
