# Generated by Django 4.0.4 on 2022-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0002_simptom_pills'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pill',
            name='text',
            field=models.TextField(default='    '),
        ),
    ]
