# Generated by Django 4.0.4 on 2022-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0003_pill_photo_pill_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='text',
        ),
        migrations.AddField(
            model_name='bodypart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
