# Generated by Django 4.0.4 on 2022-06-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0005_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='pill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='pill.pill'),
        ),
    ]
