version: '3.7'

services:
  diploma_backend:
    container_name: backend
    build: ./
    volumes:
      - ./app/:/app:rw
    ports:
      - "8001:8000"
    environment:
      PROCESS: DJANGO
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine3.15
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: aksi
      POSTGRES_PASSWORD: aksi
    logging:
      driver: none
    ports:
      - "5433:5432"

networks:
  default:
    external:
      name: diploma
