# Generated by Django 4.0.4 on 2022-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0002_simptom_pills'),
        ('order', '0002_point_title_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pills',
            field=models.ManyToManyField(related_name='orders', through='order.OrderPill', to='pill.pill'),
        ),
        migrations.AddField(
            model_name='order',
            name='simptoms',
            field=models.ManyToManyField(related_name='orders', through='order.OrderSimptom', to='pill.simptom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.point'),
        ),
        migrations.AlterField(
            model_name='orderpill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pills', to='order.order'),
        ),
        migrations.AlterField(
            model_name='ordersimptom',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_simptoms', to='order.order'),
        ),
    ]
