# Generated by Django 4.0.4 on 2022-06-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0006_alter_text_pill'),
        ('doctor', '0001_initial'),
        ('order', '0003_order_pills_order_simptoms_alter_order_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_declined', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('decline_reason', models.CharField(blank=True, max_length=1024, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_decision', to='order.order')),
            ],
            options={
                'verbose_name': 'Order decision',
                'verbose_name_plural': 'Order decisions',
            },
        ),
        migrations.CreateModel(
            name='OrderDecisionPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('order_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pills', to='order.orderdecision')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='pill.pill')),
            ],
            options={
                'verbose_name': 'Order decision pill',
                'verbose_name_plural': 'Order decision pills',
            },
        ),
    ]
