# Generated by Django 4.0.4 on 2022-06-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdecision_orderdecisionpill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdecision',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='orderdecision',
            name='is_declined',
        ),
    ]
