# Generated by Django 4.0.4 on 2022-06-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderdecision_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
