# Generated by Django 4.0.4 on 2022-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='on_destination_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
